language: node_js
node_js:
  - "8"
install: npm install
script: hexo generate && hexo server
deploy: 
  provider: pages
  skip_cleanup: true
  github_token: YTLjMEkTIKs1HoFvfJBTzw
  on:
    branch: master