sudo: false
language: node_js
node_js:
  - "8"
install: npm install
script: hexo generate
deploy: 
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  keep_history: true
  on:
    branch: master
  local_dir: public